name: 01 Basic Workflow
run-name: ${{github.actor}}의 기초 워크플로우 

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@v4
    
      - name: 메세지 출력
        run: echo "Hello, World! And Githubactions is awesome! This is my first workflow."
    
      - name: 현재 디렉터리 확인
        run: pwd

      - name: 파일 목록 확인
        run: ls -al